"""tsn info column

Revision ID: 8c5e0c2ee6b0
Revises: b801172c72fb
Create Date: 2022-11-04 15:42:47.734303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5e0c2ee6b0'
down_revision = 'b801172c72fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tsn', sa.Column('tsn_mapping_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tsn', 'tsn_mapping_info')
    # ### end Alembic commands ###
