"""info column

Revision ID: b801172c72fb
Revises: d95816664790
Create Date: 2022-11-04 15:22:50.062186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b801172c72fb'
down_revision = 'd95816664790'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spgz', sa.Column('mapping_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spgz', 'mapping_info')
    # ### end Alembic commands ###
